### ISSUE TITLE
Figure out what to do with message byte size

### ISSUE THREAD

**Issue by akalin-keybase** [keybase/go-framed-msgpack-rpc#7]
See https://github.com/keybase/go-framed-msgpack-rpc/blob/master/packetizer.go#L30 (the `l` parameter).

We should probably upper-bound it / cross-check it against the actual decoded length / avoid reading more than that number of bytes.

**Comment by maxtaco** [comment]
So my original thought was just to read in that many bytes from the stream, and them to decode the incoming message with msgpack, using arbitrary maps/arrays and no specific types that the applications might know about.  But that seemed rather wasteful and additional memcopy.  The plan that's currently in use tries to delay decoding of msgpack into Go structs so that the application can unmarshal directly into is ultimate form.

One plan might be to have the application library pass an `interface{}` into the RPC library and use reflection to figure out how the decoding should go (like the msgpack library itself), but I was trying to avoid that.

FWIW, this framing feature is extremely useful in JavaScript, where, in the absence of threads, it's harder to keep track of decoding state across TCP packet arrivals.  So even if it's not used here, it doesn't mean that it's not useful to the overall system.

But I agree, if it's convenient to sanity-check here, then it's definitely worth it to do so.

**Comment by jzila** [comment]
We can sanity check without marshaling into the final data structure. I've cleaned up that code a lot but it's a bit conflated with other attempted refactors :(. I'll see if I can extract it.
